version: '3.8'

services:
  web:
    build:
      context: ./web
    container_name: web-app
    ports:
      - '3000:3000'
    depends_on:
      - server
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/app
    working_dir: /app
    command: npm run dev

  postgres:
    image: postgres:17
    container_name: pg_posts
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=posts_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/src/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql # Uncomment to seed the database on startup

  server:
    build:
      context: ./server
    container_name: server-app
    ports:
      - '4000:4000'
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=posts_db
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKER=kafka:29092
    volumes:
      []
      # - ./server:/app
    working_dir: /app
    command: npm run dev

  redis:
    image: redis:alpine
    container_name: redis_posts
    ports:
      - '6379:6379'

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - '12181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.6.1 # ✅ explicitly use pre-KRaft version
    container_name: kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  pgdata:
